/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AppAuthedRouteImport } from './routes/_app/_authed'
import { Route as AppAuthedIndexRouteImport } from './routes/_app/_authed/index'
import { Route as AppAuthedProjectsRouteImport } from './routes/_app/_authed/projects'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthedRoute = AppAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => AppRoute,
} as any)
const AppAuthedIndexRoute = AppAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAuthedRoute,
} as any)
const AppAuthedProjectsRoute = AppAuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects': typeof AppAuthedProjectsRoute
  '/': typeof AppAuthedIndexRoute
}
export interface FileRoutesByTo {
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/projects': typeof AppAuthedProjectsRoute
  '/': typeof AppAuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/_authed': typeof AppAuthedRouteWithChildren
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_app/_authed/projects': typeof AppAuthedProjectsRoute
  '/_app/_authed/': typeof AppAuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth/confirm' | '/auth/sign-in' | '/projects' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth/confirm' | '/auth/sign-in' | '/projects' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_authed'
    | '/auth/confirm'
    | '/auth/sign-in'
    | '/_app/_authed/projects'
    | '/_app/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_authed': {
      id: '/_app/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppAuthedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_authed/': {
      id: '/_app/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppAuthedIndexRouteImport
      parentRoute: typeof AppAuthedRoute
    }
    '/_app/_authed/projects': {
      id: '/_app/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppAuthedProjectsRouteImport
      parentRoute: typeof AppAuthedRoute
    }
  }
}

interface AppAuthedRouteChildren {
  AppAuthedProjectsRoute: typeof AppAuthedProjectsRoute
  AppAuthedIndexRoute: typeof AppAuthedIndexRoute
}

const AppAuthedRouteChildren: AppAuthedRouteChildren = {
  AppAuthedProjectsRoute: AppAuthedProjectsRoute,
  AppAuthedIndexRoute: AppAuthedIndexRoute,
}

const AppAuthedRouteWithChildren = AppAuthedRoute._addFileChildren(
  AppAuthedRouteChildren,
)

interface AppRouteChildren {
  AppAuthedRoute: typeof AppAuthedRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAuthedRoute: AppAuthedRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
